/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import Connection.DatabaseConnection;
import static JFrames.Objects.con;
import static JFrames.Objects.cst;
import static JFrames.Objects.pst;
import static JFrames.Objects.rs;

/**
 *
 * @author Joshua C. Magoliman
 */
public class JFrame_ShelfProfile extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_ShelfProfile
     */
    public static int shelfId;

    public JFrame_ShelfProfile() {
        initComponents();
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
        con = dbc.getConnection();
        setIcon();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDeleteOrCancel = new javax.swing.JButton();
        btnEditOrUpdate = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblShelfTitle = new javax.swing.JLabel();
        txtShelf = new javax.swing.JTextField();
        lblShelf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setMaximumSize(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(1294, 447));
        jPanel1.setRequestFocusEnabled(false);

        btnDeleteOrCancel.setBackground(java.awt.Color.black);
        btnDeleteOrCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteOrCancel.setForeground(java.awt.Color.white);
        btnDeleteOrCancel.setText("DELETE");
        btnDeleteOrCancel.setBorder(null);
        btnDeleteOrCancel.setBorderPainted(false);
        btnDeleteOrCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteOrCancel.setFocusPainted(false);
        btnDeleteOrCancel.setFocusable(false);
        btnDeleteOrCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrCancelActionPerformed(evt);
            }
        });

        btnEditOrUpdate.setBackground(java.awt.Color.black);
        btnEditOrUpdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditOrUpdate.setForeground(java.awt.Color.white);
        btnEditOrUpdate.setText("EDIT");
        btnEditOrUpdate.setBorder(null);
        btnEditOrUpdate.setBorderPainted(false);
        btnEditOrUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditOrUpdate.setFocusPainted(false);
        btnEditOrUpdate.setFocusable(false);
        btnEditOrUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditOrUpdateActionPerformed(evt);
            }
        });

        btnClose.setBackground(java.awt.Color.black);
        btnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClose.setForeground(java.awt.Color.white);
        btnClose.setText("CLOSE");
        btnClose.setBorder(null);
        btnClose.setBorderPainted(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.setFocusable(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblShelfTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblShelfTitle.setForeground(java.awt.Color.white);
        lblShelfTitle.setText("SHELF PROFILE");

        txtShelf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtShelf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtShelf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtShelfKeyTyped(evt);
            }
        });

        lblShelf.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblShelf.setForeground(java.awt.Color.white);
        lblShelf.setText("Shelf");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblShelf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditOrUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnDeleteOrCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblShelfTitle)
                        .addGap(166, 166, 166))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblShelfTitle)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShelf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteOrCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditOrUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ICON.png")));
    }

    private void enabled() {
        txtShelf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtShelf.requestFocus();
        txtShelf.setFocusable(true);
    }

    private void deleting() {
        try {
            cst = con.prepareCall("{call sp_DeleteExistingShelf(?)}");
            cst.setInt(1, shelfId);
            if (cst.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(this, "Successfully Deleted!", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }

    private void cancelling() {
        reset();
        retrieveCurrentInfo();
    }
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditOrUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditOrUpdateActionPerformed
        switch (btnEditOrUpdate.getText()) {
            case "EDIT":
                btnEditOrUpdate.setText("UPDATE");
                btnDeleteOrCancel.setText("CANCEL");
                btnClose.setEnabled(false);
                enabled();
                break;
            case "UPDATE":
                int P = JOptionPane.showConfirmDialog(null, " Are you sure want to update?", "ATTENTION", JOptionPane.YES_NO_OPTION);
                if (P == JOptionPane.YES_OPTION) //(P==0) //YES FOR 0 NO FOR 1
                {
                    validation();
                }
                break;
        }
    }//GEN-LAST:event_btnEditOrUpdateActionPerformed

    private void btnDeleteOrCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrCancelActionPerformed
        if (btnDeleteOrCancel.getText().equals("DELETE")) {
            int P = JOptionPane.showConfirmDialog(null, " Are you sure want to delete?", "ATTENTION", JOptionPane.YES_NO_OPTION);
            if (P == JOptionPane.YES_OPTION) //(P==0) //YES FOR 0 NO FOR 1
            {
                deleting();
            }
        } else if (btnDeleteOrCancel.getText().equals("CANCEL")) {
            int P = JOptionPane.showConfirmDialog(null, " Are you sure want to cancel?", "ATTENTION", JOptionPane.YES_NO_OPTION);
            if (P == JOptionPane.YES_OPTION) //(P==0) //YES FOR 0 NO FOR 1
            {
                cancelling();
            }
        }
    }//GEN-LAST:event_btnDeleteOrCancelActionPerformed

    private void txtShelfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtShelfKeyTyped
        if (txtShelf.getText().length() >= 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txtShelfKeyTyped
    private void validation() {
        if (txtShelf.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Shelf Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtShelf.requestFocus();
        } else {
            checkingShelf();
        }
    }

    private void checkingShelf() {
        try {
            pst = con.prepareStatement("SELECT * FROM tbl_shelfs WHERE shelf = ?");
            pst.setString(1, txtShelf.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "This Shelf is already taken!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            } else {
                updating();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }

    private void updating() {
        try {
            cst = con.prepareCall("{call sp_UpdateExistingShelf(?, ?)}");
            cst.setString("param_shelf", txtShelf.getText());
            cst.setInt("param_id", shelfId);
            if (cst.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(this, "Successfully Updated!", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);
            } else {
                reset();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }

    private void reset() {
        try {
            txtShelf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            lblShelf.requestFocus();
            txtShelf.setFocusable(false);
            btnClose.setEnabled(true);
            btnEditOrUpdate.setText("EDIT");
            btnDeleteOrCancel.setText("DELETE");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }

    private void retrieveCurrentInfo() {
        try {
            pst = con.prepareStatement("SELECT * FROM tbl_shelfs WHERE id = ?");
            pst.setInt(1, shelfId);
            rs = pst.executeQuery();
            if (rs.next()) {
                txtShelf.setText(rs.getString(2));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_ShelfProfile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_ShelfProfile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_ShelfProfile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_ShelfProfile.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_ShelfProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDeleteOrCancel;
    private javax.swing.JButton btnEditOrUpdate;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblShelf;
    private javax.swing.JLabel lblShelfTitle;
    public javax.swing.JTextField txtShelf;
    // End of variables declaration//GEN-END:variables
}
