/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Connection.DatabaseConnection;
import static JFrames.Objects.con;
import static JFrames.Objects.cst;
import static JFrames.Objects.pst;
import static JFrames.Objects.rs;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Joshua C. Magoliman
 */
public class JFrame_BookAdd extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_BookAdd
     */
    private int autoIncrementIdValue, subjectIdNumber, shelfIdNumber;
    private String dateToday, timeToday;

    public JFrame_BookAdd() {
        initComponents();
        DatabaseConnection dbc = DatabaseConnection.getDatabaseConnection();
        con = dbc.getConnection();
        setIcon();
        reset();
        autoIncrementForID();
        setDateAndTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        lblRFID = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblAuthors = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        lblCopyrightYear = new javax.swing.JLabel();
        lblOriginalTotalPages = new javax.swing.JLabel();
        lblCurrentTotalPages = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblShelf = new javax.swing.JLabel();
        cmbShelf = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaPublisher = new javax.swing.JTextArea();
        txtRFID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareaAuthors = new javax.swing.JTextArea();
        txtCopyrightYear = new javax.swing.JTextField();
        txtOriginalTotalPages = new javax.swing.JTextField();
        txtCurrentTotalPages = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        cmbSubject = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD NEW BOOK");
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setMaximumSize(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(1294, 447));
        jPanel1.setRequestFocusEnabled(false);

        txtTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTitleKeyTyped(evt);
            }
        });

        lblRFID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblRFID.setText("RFID");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTitle.setText("Title");

        lblSubject.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblSubject.setText("Subject");

        lblAuthors.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthors.setText("Authors");

        lblPublisher.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblPublisher.setText("Publisher");

        lblCopyrightYear.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblCopyrightYear.setText("Copyright Year");

        lblOriginalTotalPages.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblOriginalTotalPages.setText("Original Total Pages");

        lblCurrentTotalPages.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblCurrentTotalPages.setText("Current Total Pages");

        lblQuantity.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblQuantity.setText("Quantity");

        lblShelf.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblShelf.setText("Shelf");

        cmbShelf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbShelf.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cmbShelf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbShelfItemStateChanged(evt);
            }
        });

        txtareaPublisher.setColumns(20);
        txtareaPublisher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtareaPublisher.setRows(5);
        txtareaPublisher.setAutoscrolls(false);
        txtareaPublisher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtareaPublisherKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtareaPublisher);

        txtRFID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRFID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFIDKeyTyped(evt);
            }
        });

        txtareaAuthors.setColumns(20);
        txtareaAuthors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtareaAuthors.setRows(5);
        txtareaAuthors.setAutoscrolls(false);
        txtareaAuthors.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtareaAuthorsKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtareaAuthors);

        txtCopyrightYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCopyrightYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCopyrightYearKeyTyped(evt);
            }
        });

        txtOriginalTotalPages.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOriginalTotalPages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOriginalTotalPagesKeyTyped(evt);
            }
        });

        txtCurrentTotalPages.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCurrentTotalPages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurrentTotalPagesKeyTyped(evt);
            }
        });

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setForeground(java.awt.Color.white);
        btnBack.setText("BACK");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.setFocusable(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 153, 0));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setForeground(java.awt.Color.white);
        btnAdd.setText("ADD");
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setFocusable(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cmbSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSubject.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cmbSubject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSubjectItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblQuantity)
                            .addComponent(lblCurrentTotalPages)
                            .addComponent(lblShelf))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCurrentTotalPages)
                            .addComponent(txtQuantity)
                            .addComponent(cmbShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPublisher)
                            .addComponent(lblOriginalTotalPages)
                            .addComponent(lblCopyrightYear)
                            .addComponent(lblAuthors)
                            .addComponent(lblSubject)
                            .addComponent(lblTitle)
                            .addComponent(lblRFID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtCopyrightYear)
                            .addComponent(jScrollPane2)
                            .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOriginalTotalPages, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRFID, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRFID)
                    .addComponent(txtRFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubject)
                    .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAuthors)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublisher))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCopyrightYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCopyrightYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOriginalTotalPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOriginalTotalPages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurrentTotalPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentTotalPages))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShelf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1103, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ICON.png")));
    }

    private void autoIncrementForID() {
        try {
            String sql = "SELECT (MAX(id) + 1) from tbl_books";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                autoIncrementIdValue = rs.getInt(1);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }

    private void reset() {
        txtRFID.setText("");
        txtTitle.setText("");
        retrieveSubjects();
        cmbSubject.setSelectedItem("None");
        txtareaAuthors.setText("");
        txtareaPublisher.setText("");
        txtCopyrightYear.setText("");
        txtOriginalTotalPages.setText("");
        txtCurrentTotalPages.setText("");
        txtQuantity.setText("");
        cmbShelf.setSelectedItem("None");
        txtRFID.requestFocus();
        btnBack.setText("BACK");
        retrieveShelfs();
    }

    private void setDateAndTime() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        dateToday = s.format(d);
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("hh:mm:ss a");
                timeToday = simpleDateFormat.format(date);
            }
        }).start();
    }

    private void retrieveSubjects() {
        try {
            int maximumSubjectNumber;
            pst = con.prepareStatement("SELECT MAX(id) FROM tbl_subjects");
            rs = pst.executeQuery();
            if (rs.next()) {
                maximumSubjectNumber = rs.getInt(1);
                cmbSubject.addItem("None");
                for (int startNumber = 1; startNumber <= maximumSubjectNumber; startNumber = startNumber + 1) {
                    pst = con.prepareStatement("SELECT * FROM tbl_subjects WHERE id = ?");
                    pst.setInt(1, startNumber);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        String subject = "";
                        subject = rs.getString("subject");
                        cmbSubject.addItem(subject);
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }

    private void retrieveShelfs() {
        try {
            int maximumShelfNumber;
            pst = con.prepareStatement("SELECT MAX(id) FROM tbl_shelfs");
            rs = pst.executeQuery();
            if (rs.next()) {
                maximumShelfNumber = rs.getInt(1);
                cmbShelf.addItem("None");
                for (int startNumber = 1; startNumber <= maximumShelfNumber; startNumber = startNumber + 1) {
                    pst = con.prepareStatement("SELECT * FROM tbl_shelfs WHERE id = ?");
                    pst.setInt(1, startNumber);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        String shelf = "";
                        shelf = rs.getString("shelf");
                        cmbShelf.addItem(shelf);
                    }
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }
    private void txtTitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTitleKeyTyped
        if (txtTitle.getText().length() >= 60) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTitleKeyTyped

    private void txtRFIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFIDKeyReleased
        if (txtRFID.getText().equals("")) {
            btnBack.setText("BACK");
        } else {
            btnBack.setText("CANCEL");
        }
    }//GEN-LAST:event_txtRFIDKeyReleased

    private void txtRFIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFIDKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtRFID.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRFIDKeyTyped

    private void txtCopyrightYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCopyrightYearKeyTyped
        if (txtCopyrightYear.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCopyrightYearKeyTyped

    private void txtOriginalTotalPagesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalTotalPagesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtOriginalTotalPages.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtOriginalTotalPagesKeyTyped

    private void txtCurrentTotalPagesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurrentTotalPagesKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtCurrentTotalPages.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCurrentTotalPagesKeyTyped

    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtQuantity.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantityKeyTyped
    private void validation() {
        if (txtRFID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No RFID Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtRFID.requestFocus();
        } else if (txtTitle.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Title Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtTitle.requestFocus();
        } else if (cmbSubject.getSelectedItem().equals("None")) {
            JOptionPane.showMessageDialog(this, "No Subject Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            cmbSubject.requestFocus();
        } else if (txtareaAuthors.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Authors Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtareaAuthors.requestFocus();
        } else if (txtareaPublisher.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Publisher Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtareaPublisher.requestFocus();
        } else if (txtCopyrightYear.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Copyright Year Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtCopyrightYear.requestFocus();
        } else if (txtOriginalTotalPages.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Original Total Pages Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtOriginalTotalPages.requestFocus();
        } else if (txtCurrentTotalPages.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Current Total Pages Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtCurrentTotalPages.requestFocus();
        } else if (txtQuantity.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Quantity Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
        } else if (cmbShelf.getSelectedItem().equals("None")) {
            JOptionPane.showMessageDialog(this, "No Shelf Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            cmbShelf.requestFocus();
        } else {
            checkingRFID();
        }
    }

    private void checkingRFID() {
        try {
            pst = con.prepareStatement("SELECT * FROM tbl_books WHERE rfid = ?");
            pst.setString(1, txtRFID.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "This RFId is already taken!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            } else {
                creatingBook();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }

    private void creatingBook() {
        try {
            cst = con.prepareCall("{call sp_InsertNewBook(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}");
            cst.setInt("param_id", autoIncrementIdValue);
            cst.setString("param_rfid", txtRFID.getText());
            cst.setString("param_title", txtTitle.getText());
            cst.setInt("param_subject_id", subjectIdNumber);
            cst.setString("param_authors", txtareaAuthors.getText());
            cst.setString("param_publisher", txtareaPublisher.getText());
            cst.setString("param_copyright_year", txtCopyrightYear.getText());
            cst.setInt("param_original_totalpages", Integer.parseInt(txtOriginalTotalPages.getText()));
            cst.setInt("param_current_totalpages", Integer.parseInt(txtCurrentTotalPages.getText()));
            cst.setInt("param_quantity", Integer.parseInt(txtQuantity.getText()));
            cst.setString("param_date", dateToday);
            cst.setString("param_time", timeToday);
            cst.setInt("param_shelf_id", shelfIdNumber);
            cst.setInt("param_user_id", JFrame_Main.accountId);
            if (cst.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(this, "Successfully Added!");
                reset();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
        }
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        validation();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (btnBack.getText().equals("BACK")) {
            this.hide();
            new JFrame_BookList().setVisible(true);
        } else {
            int question = JOptionPane.showConfirmDialog(null, "Are you sure want to cancel?", "ATTENTION", JOptionPane.YES_NO_OPTION);
            if (question == JOptionPane.YES_OPTION) //(P==0) //YES FOR 0 NO FOR 1
            {
                this.hide();
                new JFrame_BookList().setVisible(true);
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtareaPublisherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtareaPublisherKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            if (!txtareaPublisher.getText().equals("")) {
                txtCopyrightYear.requestFocus();
            }
        }
    }//GEN-LAST:event_txtareaPublisherKeyPressed

    private void cmbShelfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbShelfItemStateChanged
        if (!cmbShelf.getSelectedItem().equals("None")) {
            try {
                pst = con.prepareStatement("SELECT * FROM tbl_shelfs WHERE shelf = ?");
                pst.setString(1, cmbShelf.getSelectedItem().toString());
                rs = pst.executeQuery();
                if (rs.next()) {
                    shelfIdNumber = rs.getInt("id");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmbShelfItemStateChanged

    private void cmbSubjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSubjectItemStateChanged
        if (!cmbSubject.getSelectedItem().equals("None")) {
            try {
                pst = con.prepareStatement("SELECT * FROM tbl_subjects WHERE subject = ?");
                pst.setString(1, cmbSubject.getSelectedItem().toString());
                rs = pst.executeQuery();
                if (rs.next()) {
                    subjectIdNumber = rs.getInt("id");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_cmbSubjectItemStateChanged

    private void txtareaAuthorsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtareaAuthorsKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            if (!txtareaAuthors.getText().equals("")) {
                txtareaPublisher.requestFocus();
            }
        }
    }//GEN-LAST:event_txtareaAuthorsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_StudentList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_BookAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbShelf;
    private javax.swing.JComboBox<String> cmbSubject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuthors;
    private javax.swing.JLabel lblCopyrightYear;
    private javax.swing.JLabel lblCurrentTotalPages;
    private javax.swing.JLabel lblOriginalTotalPages;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblRFID;
    private javax.swing.JLabel lblShelf;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTitle;
    public javax.swing.JTextField txtCopyrightYear;
    public javax.swing.JTextField txtCurrentTotalPages;
    public javax.swing.JTextField txtOriginalTotalPages;
    public javax.swing.JTextField txtQuantity;
    public javax.swing.JTextField txtRFID;
    public javax.swing.JTextField txtTitle;
    private javax.swing.JTextArea txtareaAuthors;
    private javax.swing.JTextArea txtareaPublisher;
    // End of variables declaration//GEN-END:variables
}
